In [1]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.transforms import ToTensor
import torchvision.models as models
from PIL import Image
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sb

from functools import partial
from collections import OrderedDict

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_recall_fscore_support
from sklearn.preprocessing import MinMaxScaler, StandardScaler

import time
import pickle

In [6]:
hidden_width = 32
hidden_nblocks = 4
train_max_epoch = 50
max_iterations = 10

chip_size = 32

data_root = "geomorph_data"
n_channels = len(os.listdir(data_root))

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
L2_param = 1e-5

label_name = "visible_ice"
num_classes = 5
output_size = 5

sm = nn.Softmax(dim=-1)

In [7]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
print(input)
print(target)
print(output)

tensor([[-0.0144, -0.9494, -0.7305, -0.9166,  0.2680],
        [-1.7730,  0.1862, -0.8611,  2.0290,  1.0670],
        [-0.1772,  0.6253, -0.1234, -0.3409, -0.6544]], requires_grad=True)
tensor([4, 3, 0])
tensor(1.0780, grad_fn=<NllLossBackward>)


In [8]:
m = nn.Softmax(dim=-1)
# m = nn.Sigmoid()
input = torch.randn(2,3)
print(input)
output = m(input)
print(output)

tensor([[0.6591, 0.4579, 2.2992],
        [1.2257, 0.2111, 0.8404]])
tensor([[0.1434, 0.1173, 0.7393],
        [0.4895, 0.1775, 0.3330]])


In [9]:
class mlp(nn.Module):
        def __init__(self, input_size, output_size = 1, hidden_width = 20, hidden_nblocks = 2):
            super(mlp, self).__init__()
            self.input_size = input_size
            self.output_size = output_size
            
            self.hidden_width = hidden_width
            self.hidden_nblocks = hidden_nblocks
            
            self.fc1 = nn.Linear(self.input_size, self.hidden_width)
            self.fc2 = nn.Linear(self.hidden_width,self.hidden_width)
            self.fc3 = nn.Linear(self.hidden_width, self.output_size)
            
            self.relu = torch.nn.ReLU()
            self.end= torch.nn.Softmax(dim = -1) ## sigmoid for multi-label, softmax for multi-class (mutually exclusive)
            
            self.dropout = nn.Dropout(0.25)
            
        def forward(self, x, film_params):
            out = self.fc1(x)
            out = self.relu(out)
            
            
            for i in range(self.hidden_nblocks):
                out = self.fc2(out)
                
                # ------- film layer -----------
                start = i * hidden_width * 2
                mid = start + hidden_width
                end = mid + hidden_width
                
                gamma = film_params[:, start : mid]
                beta = film_params[:, mid : end]
                
#                 print(out.shape)
#                 print(gamma.shape)
#                 print(beta.shape)
                
                out = out * gamma
                out += beta
                # ------- film layer -----------
                # out = self.dropout(out)
                out = self.relu(out)
            
            out = self.fc3(out)
            # out = self.end(out)
            return out

## Dataset

In [10]:
# scaler = MinMaxScaler()
def normalize(values):
    # zero mean, unit variance
    value_mean = values.mean()
    value_std = values.std()
    return (values-values_mean)/values_std

def normalize_maxmin(values):
    # range from 0 to 1
    (values-values.min())/(values.max()-values.min())


def get_scaler(data):
    scaler = StandardScaler()
    print(data)
    scaler.fit(data)
    return scaler
    
def preprocess_df(df):
    # convert timecodes to year and month columns
    datetimes = pd.to_datetime(df['time'])
    df['month'] = datetimes.dt.month
    df['year'] = datetimes.dt.year

    df['month_cyclic'] = 7 - abs(df['month'] - 7)
    
    data = df[['latitude', 'longitude', 'depth', 'year', 'month_cyclic']]
    scaler = StandardScaler()
    scaler.fit(data)
    df[['lat_norm', 'lng_norm', 'depth_norm', 'year_norm', 'month_cyclic_norm']] = scaler.transform(df[['latitude', 'longitude', 'depth', 'year', 'month_cyclic']])
    
    return scaler


#     df['lat_norm'] = normalize(df['latitude'])
#     df['lng_norm'] = normalize(df['longitude'])
#     df['depth_norm'],  = normalize(df['depth'])
#     df['year_norm'] = normalize(df['year'])
#     df['month_cyclic_norm'] = normalize(df['month_cyclic'])

df = pd.read_csv('data_stephen_fix_header.csv', header=[0])
scaler = preprocess_df(df)
    
print(df.shape[0])
print(df['borehole'].nunique())
df.head()

2837
566


latitude  longitude                  time   borehole  depth  frozen  \
0  69.16162 -133.08682  2012-03-21T00:00:00Z  0170-1-10   0.15       0   
1  69.16162 -133.08682  2012-03-21T00:00:00Z  0170-1-10   0.85       1   
2  69.16162 -133.08682  2012-03-21T00:00:00Z  0170-1-10   1.90       1   
3  69.16162 -133.08682  2012-03-21T00:00:00Z  0170-1-10   5.40       1   
4  69.16105 -133.08880  2012-03-21T00:00:00Z  0170-1-12   1.20       1   

  cryostructures     visible_ice ASTM_2488    materials  ...  top_of_interval  \
0            NaN             NaN   TOPSOIL     Organics  ...              0.0   
1            NaN        Pure ice       ICE          Ice  ...              0.3   
2             Nf  No visible ice     SW-SM  Coarse till  ...              1.4   
3             Nf  No visible ice     GW-GM  Coarse till  ...              2.4   
4             Nf  No visible ice     GP-GM  Coarse till  ...              0.0   

   bottom_of_interval  month  year  month_cyclic  lat_norm  lng_norm  \
0                 0.3      3  2012             3  1.439946  1.851455   
1                 1.4      3  2012             3  1.439946  1.851455   
2                 2.4      3  2012             3  1.439946  1.851455   
3                 8.4      3  2012             3  1.439946  1.851455   
4                 2.4      3  2012             3  1.437795  1.842620   

   depth_norm  year_norm  month_cyclic_norm  
0   -1.024190  -1.164992          -1.225295  
1   -0.835900  -1.164992          -1.225295  
2   -0.553466  -1.164992          -1.225295  
3    0.387982  -1.164992          -1.225295  
4   -0.741756  -1.164992          -1.225295  

[5 rows x 21 columns]

In [15]:
print(df.latitude.max())
print(df.latitude.min())
print(df.longitude.max())
print(df.longitude.min())

69.44755
68.36933
-132.89346
-133.82843


In [16]:
df['visible_ice'].replace(['None'], 'No visible ice', regex=True, inplace=True)

ordered_ice = ['No visible ice', 'Low', "Medium to high", 'High', 'Pure ice']
df['visible_ice'] = pd.Series(pd.Categorical(df['visible_ice'], categories=ordered_ice, ordered=True))

df2 = df.dropna(subset=['visible_ice'])

df2.tail()

latitude  longitude                  time           borehole  depth  \
2832  68.38262 -133.71211  2013-04-27T00:00:00Z  W14103137-S6-BH15   5.45   
2833  68.38262 -133.71211  2013-04-27T00:00:00Z  W14103137-S6-BH15   8.65   
2834  68.38386 -133.70967  2013-04-27T00:00:00Z  W14103137-S6-BH16   0.05   
2835  68.38386 -133.70967  2013-04-27T00:00:00Z  W14103137-S6-BH16   0.35   
2836  68.38386 -133.70967  2013-04-27T00:00:00Z  W14103137-S6-BH16   4.85   

      frozen cryostructures     visible_ice ASTM_2488 materials  ...  \
2832       1         Nf/Nbn  No visible ice       NaN      Till  ...   
2833       1            Nbn  No visible ice       NaN      Till  ...   
2834       0            NaN  No visible ice  ORGANICS  Organics  ...   
2835       0            NaN  No visible ice       NaN      Till  ...   
2836       1            Nbn  No visible ice       NaN      Till  ...   

      top_of_interval  bottom_of_interval  month  year  month_cyclic  \
2832              2.7                 8.2      4  2013             4   
2833              8.2                 9.1      4  2013             4   
2834              0.0                 0.1      4  2013             4   
2835              0.1                 0.6      4  2013             4   
2836              0.6                 9.1      4  2013             4   

      lat_norm  lng_norm  depth_norm  year_norm  month_cyclic_norm  
2832 -1.499167 -0.938559    0.401431  -0.319053           0.736422  
2833 -1.499167 -0.938559    1.262184  -0.319053           0.736422  
2834 -1.494489 -0.927672   -1.051089  -0.319053           0.736422  
2835 -1.494489 -0.927672   -0.970393  -0.319053           0.736422  
2836 -1.494489 -0.927672    0.240040  -0.319053           0.736422  

[5 rows x 21 columns]

In [17]:
# check None values have been replaced
len(df2[df2['visible_ice'] == 'None'])

0

In [18]:
df2['visible_ice_code'] =  df2['visible_ice'].cat.codes
print(df2['visible_ice'].unique())
print(df2['visible_ice_code'].unique())
df2['visible_ice']

['Pure ice', 'No visible ice', 'High', 'Medium to high', 'Low']
Categories (5, object): ['No visible ice' < 'Low' < 'Medium to high' < 'High' < 'Pure ice']
[4 0 3 2 1]


<ipython-input-18-b83c4bbc5a30>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['visible_ice_code'] =  df2['visible_ice'].cat.codes


1             Pure ice
2       No visible ice
3       No visible ice
4       No visible ice
5       No visible ice
             ...      
2832    No visible ice
2833    No visible ice
2834    No visible ice
2835    No visible ice
2836    No visible ice
Name: visible_ice, Length: 2752, dtype: category
Categories (5, object): ['No visible ice' < 'Low' < 'Medium to high' < 'High' < 'Pure ice']

In [19]:
# visible_ice = pd.get_dummies(df2.visible_ice)
# bin_visible_ice = (~visible_ice['No visible ice'].astype('bool')).astype('int')
# bin_visible_ice.value_counts()

# df2['visible_ice'] = bin_visible_ice

# df2.head()

In [20]:
df3 = df.dropna(subset=['materials'])
df3['materials'].replace(['ICE'], 'Ice', regex=True, inplace=True)
df3['materials'].replace(['ice'], 'Ice', regex=True, inplace=True)

In [21]:
dm_materials = pd.get_dummies(df3.materials)
df3['material_ice'] = dm_materials['Ice']

In [22]:
class Geo90Dataset(Dataset):
    def __init__(self, data_root, df, base_lat, base_lng, chip_size=32):
        
        self.base_lat = base_lat
        self.base_lng = base_lng
        
        self.df = df
        
        self.chip_size = chip_size
        
        self.trans = transforms.ToTensor()
        
        self.n_channels = n_channels
        self.preloaded = torch.ones(self.n_channels, 6000, 6000)
        
        for i, file in enumerate(os.listdir(data_root)):
            # name = file.split('_')[0]
            # print(name)
            self.preloaded[i] = self.trans(Image.open(data_root + os.path.sep + file))
        
        
        print('Dataset initialized')
        
    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        
        bh_id = row.at['borehole']
        lat = row.at['latitude']
        lng = row.at['longitude']
        

        pixel_len = 5/6000
        

        lat_index_start = np.round((self.base_lat - lat) / pixel_len - self.chip_size/2).astype(int)
        lat_index_end = lat_index_start + self.chip_size
        
        lng_index_start = np.round((lng - self.base_lng) / pixel_len - self.chip_size/2).astype(int)
        lng_index_end = lng_index_start + self.chip_size
        
        image = self.preloaded[:, lat_index_start:lat_index_end,lng_index_start:lng_index_end]
        
        
        # surface = torch.tensor(row.filter(['depth'])).float()
        surface = torch.tensor(row.filter(['depth_norm', 'month_cyclic_norm', 'lat_norm', 'lng_norm', 'year_norm'])).float()
        
        frozen = torch.tensor(row.at['frozen']).float()
        
        # visible_ice = torch.tensor(row.at['visible_ice']).float()
        visible_ice = torch.tensor(row.at['visible_ice_code']).long()
        
        # material_ice = torch.tensor(row.at['material_ice']).float()
        
        return {'image': image, 'surface_data': surface, 'frozen': frozen,  'visible_ice': visible_ice} #'material_ice': material_ice}

## Train model

## FiLM

In [23]:
n_film_params = hidden_width * hidden_nblocks * 2

# generator = resnet18(n_channels, n_film_params)

def train_model(trainloader, testloader, print_epochs = False, loss_fn = torch.nn.BCELoss()):
    # loss: binary cross entropy

    generator = models.resnet18()
    generator.fc = nn.Linear(512, n_film_params)
    generator.conv1 = nn.Conv2d(n_channels, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    
    gen_model = generator

    # print(gen_model)

    input_size = list(full_dataset[0]['surface_data'].size())
    net_model = mlp(input_size[0],output_size, hidden_width, hidden_nblocks).to(device)
    
    gen_optimizer = torch.optim.Adam(gen_model.parameters(), weight_decay = L2_param)
    net_optimizer = torch.optim.Adam(net_model.parameters(), weight_decay = L2_param)
    
    gen_model.to(device)
    net_model.to(device)

    # --------- check back propagation ----------- -
    # net_model.fc1.weight.register_hook(lambda x: print('grad accumulated in mlp fc1'))
    # gen_first_layer = gen_model.encoder.blocks[0].blocks[0].blocks[0].conv
    # gen_first_layer.weight.register_hook(lambda x: print('grad accumulated in resnet first layer'))

    epoch_loss = np.zeros([train_max_epoch, 2])
    for epoch in range(train_max_epoch):  # loop over the dataset multiple times

        # ------------ train -----------------
        gen_model.train()
        net_model.train()
        running_loss_sum = 0.0
        for i, data in enumerate(trainloader, 0): # loop over each sample

            # get the inputs; data is a list of [inputs, labels]
            images, surface_data, labels = data['image'].to(device), data['surface_data'].to(device), data[label_name].to(device)

            
            gen_params = gen_model(images)
            predicted = net_model(surface_data, gen_params)
            predicted = torch.squeeze(predicted)
            loss = loss_fn(predicted, labels)

            gen_optimizer.zero_grad()
            net_optimizer.zero_grad()

            loss.backward()

            gen_optimizer.step()
            net_optimizer.step()

            running_loss_sum += loss.item()

        # ----------- get validation loss for current epoch --------------
        gen_model.eval()
        net_model.eval()
        validation_loss_sum = 0.0
        for i, data in enumerate(testloader, 0): # loop over each sample

            # get the inputs; data is a list of [inputs, labels]
            images, surface_data, labels = data['image'].to(device), data['surface_data'].to(device), data[label_name].to(device)

            # TODO: exammine film_params gradients / readup pytorch
            gen_params = gen_model(images)
            predicted = net_model(surface_data, gen_params)
            predicted = torch.squeeze(predicted)
            loss = loss_fn(predicted, labels)
            validation_loss_sum += loss.item()

        # ---------------- print statistics ------------------------

        running_loss = running_loss_sum / len(trainloader)
        validation_loss = validation_loss_sum / len(testloader)
        epoch_loss[epoch, :] =  [running_loss, validation_loss]
        
        if print_epochs:
            print('epoch %2d: running loss: %.5f, validation loss: %.5f' %
                          (epoch + 1, running_loss, validation_loss))

        torch.save(gen_model.state_dict(), os.path.join('mlp-resnet-models/', 'gen-epoch-{}.pt'.format(epoch+1)))
        torch.save(net_model.state_dict(), os.path.join('mlp-resnet-models/', 'net-epoch-{}.pt'.format(epoch+1)))

    if print_epochs:
        print('Finished Training')
    
    return epoch_loss

## Test model

def test_model(epoch_loss, print_model_epoch = False):
    
    # ------ select model ---------
    ind = np.argmin(epoch_loss[:, 1])
    
    generator = models.resnet18()
    generator.fc = nn.Linear(512, n_film_params)
    generator.conv1 = nn.Conv2d(n_channels, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    
    gen_model = generator

    input_size = list(full_dataset[0]['surface_data'].size())
    net_model = mlp(input_size[0],1, hidden_width, hidden_nblocks)

    gen_model.load_state_dict(torch.load('mlp-resnet-models/gen-epoch-{}.pt'.format(ind+1)))
    net_model.load_state_dict(torch.load('mlp-resnet-models/net-epoch-{}.pt'.format(ind+1)))
    
    gen_model.to(device)
    net_model.to(device)
    
    if print_model_epoch:
        print("epoch {} model selected".format(ind+1))
    
    # evaluate model on test set
    gen_model.eval()
    net_model.eval()
    with torch.no_grad():
        y_test = []
        y_pred = []
        for i, data in enumerate(testloader, 0):
            images, surface_data, labels = data['image'].to(device), data['surface_data'].to(device), data[label_name].to(device)

            # y_test.append(label.numpy().list())
            # print(label.shape)
            # print(images.shape)

            gen_params = gen_model(images)
            predicted = net_model(surface_data, gen_params)
            predicted = torch.squeeze(predicted)

            predicted = torch.round(predicted)
            # print(predicted.shape)
            lb = labels.tolist()
            pr = predicted.tolist()
            y_test.extend(lb)
            y_pred.extend(pr)
    
    arr_accuracy = accuracy_score(y_test, y_pred)
    scores = precision_recall_fscore_support(y_test, y_pred, average=None, zero_division=0)
    return arr_accuracy, scores


#     print(confusion_matrix(y_test,y_pred))
#     print(classification_report(y_test,y_pred))
#     print(accuracy_score(y_test, y_pred))

## Pure MLP

## MLP

In [24]:
class mlp_pure(nn.Module):
        def __init__(self, input_size, output_size):
            super(mlp_pure, self).__init__()
            self.input_size = input_size
            self.output_size = output_size
            
            self.hidden_size = hidden_width
            self.hidden_nblocks = hidden_nblocks
            
            self.fc1 = torch.nn.Linear(self.input_size, self.hidden_size)
            self.fc2 = torch.nn.Linear(self.hidden_size,self.hidden_size)
            self.fc3 = torch.nn.Linear(self.hidden_size, self.output_size)
            
            self.relu = torch.nn.ReLU()
            self.end = torch.nn.Softmax(dim=-1) ## sigmoid for multi-label, softmax for multi-class (mutually exclusive)
            
        def forward(self, x):
            out = self.fc1(x)
            out = self.relu(out)
            # print(out.shape)
            
            for i in range(self.hidden_nblocks):
                out = self.fc2(out)
                out = self.relu(out)
            
            out = self.fc3(out)
            # out = self.end(out)
            return out

def train_mlp(trainloader, testloader, print_epochs = False, loss_fn = torch.nn.BCELoss()):
    input_size = list(full_dataset[0]['surface_data'].size())
    surface_model = mlp_pure(input_size[0],output_size)
    
    surface_model.to(device)
    
    optimizer = torch.optim.Adam(surface_model.parameters(), weight_decay = L2_param)

    epoch_loss = np.zeros([train_max_epoch, 2])
    for epoch in range(train_max_epoch):  # loop over the dataset multiple times

        surface_model.train()
        running_loss_sum = 0.0
        for i, data in enumerate(trainloader, 0): # loop over each sample

            # get the inputs; data is a list of [inputs, labels]
            surface_data, labels = data['surface_data'].to(device), data[label_name].to(device)

            predicted = surface_model(surface_data)
            
            # print(predicted.shape)
            
            # squeeze: return tensor with all dimensions of size 1 removed
            loss = loss_fn(predicted.squeeze(), labels)

            optimizer.zero_grad()

            loss.backward()

            optimizer.step()

            running_loss_sum += loss.item()

        # ----------- get validation loss for current epoch --------------
        surface_model.eval()
        validation_loss_sum = 0.0
        for i, data in enumerate(testloader, 0): # loop over each sample

            surface_data, labels = data['surface_data'].to(device), data[label_name].to(device)

            predicted = surface_model(surface_data)
            
            loss = loss_fn(predicted.squeeze(), labels)

            validation_loss_sum += loss.item()

        # ---------------- print statistics ------------------------

        running_loss = running_loss_sum / len(trainloader)
        validation_loss = validation_loss_sum / len(testloader)
        epoch_loss[epoch, :] =  [running_loss, validation_loss]
        
        if print_epochs:
            print('epoch %2d: running loss: %.5f, validation loss: %.5f' %
                          (epoch + 1, running_loss, validation_loss))

        torch.save(surface_model.state_dict(), os.path.join('mlp-models/', 'epoch-{}.pt'.format(epoch+1)))
    
    if print_epochs:
        print('Finished Training')
        
    return epoch_loss
        
def test_mlp(epoch_loss, print_model_epoch = False):
    
    # ------ select model ---------
    ind = np.argmin(epoch_loss[:, 1])
    
    input_size = list(full_dataset[0]['surface_data'].size())
    
    surface_model = mlp_pure(input_size[0],output_size)
    surface_model.load_state_dict(torch.load('mlp-models/epoch-{}.pt'.format(ind+1)))
    
    surface_model.to(device)
    
    if print_model_epoch:
        print("epoch {} model selected".format(ind+1))
    
    # evaluate model on test set
    surface_model.eval()

    with torch.no_grad():
        y_test = []
        y_pred = []
        y_cert = []
        for i, data in enumerate(testloader, 0):
            surface_data, labels = data['surface_data'].to(device), data[label_name].to(device)

            # y_test.append(label.numpy().list())
            # print(label.shape)
            # print(images.shape)

            output = surface_model(surface_data)
            
            output = sm(output)
            # print(output)
            
            
            max_results = torch.max(output, dim= -1)
            predicted = max_results.indices
            certainty = max_results.values
            #predicted = torch.round(output)
            # print(predicted.shape)
            
            y_test.extend(labels.tolist())
            y_pred.extend(predicted.tolist())
            y_cert.extend(certainty.tolist())
            


            
    
#     print(y_test)
#     print(y_pred)
    with open("mlp-certainty/iteration_{}.txt".format(it), "wb") as fp:   #Pickling
        pickle.dump(y_cert, fp)
    #with open("test.txt", "rb") as fp:   # Unpickling
        #b = pickle.load(fp)
    arr_accuracy = accuracy_score(y_test, y_pred)
    scores = precision_recall_fscore_support(y_test, y_pred, average=None, zero_division=0)
    return arr_accuracy, scores


## Multiple Runs

In [25]:
base_lat = 70
base_lng = -135

loaded_dataset = Geo90Dataset(data_root, df2, base_lat, base_lng, chip_size)

# image = full_dataset[0]['image']
# n_channels = list(image.shape)[0]

# for data in full_dataset:
#     image = data['image']
#     for i in range(n_channels):
#         channel = image[i]
#         ind = (channel == -9999)
# #         mean_val = torch.mean(channel[~ind])
#         channel[ind] = 0
#         data['image'][i] = channel
        

Dataset initialized


### Discard samples with invalid values in image chips

In [17]:
valid_ind = []
for i, data in enumerate(loaded_dataset):
    image = data['image']
    ind  = (image == -9999)
    if ~torch.any(ind):
        valid_ind.append(i)

full_dataset = torch.utils.data.Subset(loaded_dataset, valid_ind)


print(len(loaded_dataset))
print(len(full_dataset))

2752
2717


In [18]:


train_size = int(0.8 * len(full_dataset))
test_size = len(full_dataset) - train_size

# batchsize can cause error when last leftover batchsize is 1, batchnorm cannot function on 1 sample data
batchsize = 20
while(train_size % batchsize == 1):
    batchsize+=1
print(batchsize)

train_data, test_data = torch.utils.data.random_split(full_dataset, [train_size, test_size], generator=torch.Generator().manual_seed(42))

trainloader = DataLoader(train_data, batch_size=batchsize, shuffle=True)
testloader = DataLoader(test_data, batch_size=batchsize, shuffle=True)

20


## Scale of image chips

In [19]:
# image = full_dataset[0]['image']
# n_samples = len(train_data)
# n_channels = list(image.shape)[0]

# scalers = []
# for i in range(n_channels):
#     print(i)
#     scaler = StandardScaler()
#     X = torch.empty((n_samples, chip_size, chip_size))
    
#     for j, data in enumerate(train_data):
#         #print(data['image'][i].shape)
#         # print(X[j].shape)
#         X[j] = data['image'][i]
#     X = torch.reshape(X, (-1,1))
#     #print(X)
#     # break;
#     scaler.fit(X)
#     scalers.append(scaler)
    
#     def scale_data(subset):
#         for data in subset:
#             X = data['image'][i]
#             X_flat = torch.reshape(X, (-1,1))
            
#             X_trans = scaler.transform(X_flat)
#             data['image'][i] = torch.reshape(torch.Tensor(X_trans), (chip_size, chip_size))
    
#     scale_data(train_data)
#     scale_data(test_data)
#     print("Channel {} scaled.".format(i))

In [31]:
results = np.zeros([max_iterations, num_classes*4 + 1])
# trainloader, testloader = prepare_dataloader(full_dataset)

for it in range(max_iterations):
    start = time.time()
    
    # mlp
    epoch_loss_mlp = train_mlp(trainloader,testloader, print_epochs = True, loss_fn = nn.CrossEntropyLoss())
    acc, scores = test_mlp(epoch_loss_mlp, print_model_epoch = True)
    
    #     # ------- mlp-resnet film 
#     epoch_loss = train_model(trainloader, testloader, print_epochs=True, loss_fn = nn.CrossEntropyLoss())
#     acc, scores = test_model(epoch_loss, print_model_epoch = True)
    
    # scores = precision, recall, fscore, support
    results[it, 0] = acc
    
    for j, score in enumerate(scores):
        start_ind = 1 + j*num_classes
        results[it, start_ind: start_ind + num_classes] = score

    end = time.time()
    
    print('iteration {} elapsed time: {}, accuracy : {}'.format(it+1, end-start, acc))


epoch  1: running loss: 1.47335, validation loss: 1.36664
epoch  2: running loss: 1.38815, validation loss: 1.35103
epoch  3: running loss: 1.37903, validation loss: 1.33427
epoch  4: running loss: 1.37241, validation loss: 1.33023
epoch  5: running loss: 1.36518, validation loss: 1.34114
epoch  6: running loss: 1.35300, validation loss: 1.33881
epoch  7: running loss: 1.34913, validation loss: 1.32167
epoch  8: running loss: 1.33633, validation loss: 1.31028
epoch  9: running loss: 1.32868, validation loss: 1.29821
epoch 10: running loss: 1.32486, validation loss: 1.33771
epoch 11: running loss: 1.30310, validation loss: 1.32336
epoch 12: running loss: 1.29723, validation loss: 1.31441
epoch 13: running loss: 1.28795, validation loss: 1.30517
epoch 14: running loss: 1.28120, validation loss: 1.30562
epoch 15: running loss: 1.27372, validation loss: 1.30168
epoch 16: running loss: 1.27064, validation loss: 1.31804
epoch 17: running loss: 1.26231, validation loss: 1.30066
epoch 18: runn

In [32]:
def display_table(scores):
    df = np.reshape(scores, [num_classes,4], order ='F')
    df = pd.DataFrame(df)
    
    # df.style.set_table_attributes("style='display:inline'").set_caption(mode)
    
    df.columns = ['precision', 'recall', 'f1', 'support']
    # df.index = ['unfrozen', 'frozen']
    # df.index = ['Visible ice', 'No visible ice']
    
    display(df)
    
def display_results(results):
    mean = np.mean(results, axis=0)
    std = np.std(results, axis=0)
    
    print("mean")
    display_table(mean[1:])
    
    print("std")
    display_table(std[1:])
    
    print("Accuracy mean: {}, std: {}".format(mean[0], std[0]))

display_results(results)

mean


precision    recall        f1  support
0   0.563565  0.558621  0.557598    203.0
1   0.398419  0.351316  0.370706    152.0
2   0.358434  0.497872  0.411894    141.0
3   0.000000  0.000000  0.000000     15.0
4   0.070265  0.036364  0.047561     33.0

std


precision    recall        f1  support
0   0.033424  0.062163  0.027205      0.0
1   0.019743  0.052401  0.027321      0.0
2   0.011057  0.108989  0.043609      0.0
3   0.000000  0.000000  0.000000      0.0
4   0.093961  0.050343  0.064931      0.0

Accuracy mean: 0.43786764705882353, std: 0.010261239512465341


## Display Map

In [51]:
print(df.depth.max())
print(df.depth.min())

21.1
0.0


In [2]:
latitude_max = 69.5
latitude_min = 68.3
longitude_max = -132.8
longitude_min = -133.9

n_lat = 40
n_lng = 20
n_depth = 10

lng_range = np.linspace(longitude_min, longitude_max, n_lng)
lat_range = np.linspace(latitude_min, latitude_max, n_lat)
depth_range = np.arange(0,n_depth)

grid_lng, grid_lat, grid_depth = np.meshgrid(lng_range, lat_range, depth_range)


In [3]:
df_syn = pd.DataFrame(columns=['latitude', 'longitude', 'depth', 'year', 'month'])

In [4]:
df_syn['latitude'] = grid_lat.flatten()
df_syn['longitude'] = grid_lng.flatten()
df_syn['depth'] = grid_depth.flatten()
df_syn['year'] = 2013
df_syn['month'] = 3

In [5]:
df_syn.tail()

latitude  longitude  depth  year  month
7995      69.5     -132.8      5  2013      3
7996      69.5     -132.8      6  2013      3
7997      69.5     -132.8      7  2013      3
7998      69.5     -132.8      8  2013      3
7999      69.5     -132.8      9  2013      3

In [11]:
scaler.mean_

array([  68.77996824, -133.50176278,    3.95760839, 2013.37715897,
          3.62460345])

In [12]:
df_syn = scaler.transform(df_syn)

In [13]:
df_syn

array([[-1.81088706, -1.77691568, -1.06453786, -0.31905326, -1.22529482],
       [-1.81088706, -1.77691568, -0.79555272, -0.31905326, -1.22529482],
       [-1.81088706, -1.77691568, -0.52656758, -0.31905326, -1.22529482],
       ...,
       [ 2.71663018,  3.13123246,  0.81835815, -0.31905326, -1.22529482],
       [ 2.71663018,  3.13123246,  1.08734329, -0.31905326, -1.22529482],
       [ 2.71663018,  3.13123246,  1.35632844, -0.31905326, -1.22529482]])

In [14]:
full_dataset[0]['surface_data']

NameError: name 'full_dataset' is not defined

In [226]:
# ------ select model ---------
ind = 40

input_size = list(full_dataset[0]['surface_data'].size())

surface_model = mlp_pure(input_size[0],output_size)

surface_model.load_state_dict(torch.load('mlp-models/epoch-{}.pt'.format(ind+1)))

surface_model.to(device)

# surface_model = surface_model.float()

print("epoch {} model selected".format(ind+1))

# evaluate model on synthetic set
surface_model.eval()

with torch.no_grad():
    y_pred = []
    y_cert = []
    
    surface_data= torch.from_numpy(df_syn).float().to(device)

    # y_test.append(label.numpy().list())
    # print(label.shape)
    # print(images.shape)

    output = surface_model(surface_data)

    output = sm(output)
    # print(output)
    
    # proxy for uncertainty
    # cross entropy penalizes value for not being close to 1 when it's the right category
    # saturate leading to overconfidence

    max_results = torch.max(output, dim= -1)
    predicted = max_results.indices
    certainty = max_results.values

predicted = predicted.reshape(n_lng, n_lat, n_depth)


epoch 41 model selected


In [227]:
predicted_reshaped = predicted.reshape(n_lng, n_lat, n_depth)

In [228]:
predicted.shape

torch.Size([20, 40, 10])

In [229]:
predicted_2d = torch.sum(predicted, dim = -1)

In [230]:
import gmplot as gp

In [231]:
mean_lat = df2.latitude.unique().mean()
mean_lng = df2.longitude.unique().mean()

In [232]:
grid_lng_2d, grid_lat_2d = np.meshgrid(lng_range, lat_range)
grid_lng_2d = grid_lng_2d.flatten()
grid_lat_2d = grid_lat_2d.flatten()

In [233]:
grid_lat_2d.shape

(800,)

In [234]:
predicted_2d = predicted_2d.flatten().cpu()
color_ice = ocean(predicted_2d)
len(color_ice)

800

In [235]:
color_ice_hex = [None] * len(color_ice)

In [236]:
for i, color in enumerate(color_ice):
    color_ice_hex[i] = to_hex(color)

In [237]:
gmap = gp.GoogleMapPlotter(mean_lat, mean_lng, 8, apikey = "AIzaSyAabDb0aXNQT-YabM-lFULtYeotn_I2eqA")

 
gmap.scatter(grid_lat_2d, grid_lng_2d, s = 1000, c=color_ice_hex, marker=False) #, color='#3B0B39', size=40, marker=False)
# gmap.heatmap(df2.latitude.tolist(), df2.longitude.tolist())  

# gmap.scatter(grid_lat_2d[0:2], grid_lng_2d[0:2], s = 500, c=ocean[predicted_2d[0:2]])

# Pass the absolute path
gmap.draw( "map_ice2.html" )

In [163]:
grid_lng_2d.size

200

In [238]:
predicted_2d.max()

tensor(32)

In [202]:
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
from matplotlib.colors import to_hex

In [181]:
ocean = cm.get_cmap('ocean',predicted_2d.max())

In [183]:
print(ocean(0))

(0.0, 0.5, 0.0, 1.0)


In [184]:
print(ocean(30))

(0.903225806451613, 0.9516129032258065, 0.967741935483871, 1.0)
